In [1]:
#Importo las librerías
import requests
import numpy as np

### Repaso de La clase Anterior

In [2]:
a = [1,2,3,4]

**¿Cómo puedo crear un array nuevo con el cuadrado de cada uno de estos elementos?**

In [6]:
b = []
for x in a:
    b.append(x**2)
    #b+=[x**2]
b

[1, 4, 9, 16]

**Todos los elementos de un array tienen que poseer sí o sí el mismo tipo de datos. (Verdadero / Falso)**

In [8]:
a = [1,2,3,4, "hola"]
a

[1, 2, 3, 4, 'hola']

### Librería Numpy [documentación](https://numpy.org/doc/stable/index.html)

NumPy es el paquete fundamental para la computación científica con Python.

Contiene, entre otras cosas:

Un poderoso elemento: los arrays de N-dimensiones (ND arrays)

Funciones para realizar cálculos y operaciones matemáticas con arrays de forma muy eficiente (vectorización)

Operaciones de álgebra lineal, generación de números aleatorios, entre otras funcionalidades de computación científica

Esto permite que NumPy se integre de manera rápida y sin problemas con una amplia variedad de bases de datos.

**¿Por qué utilizar arrays?**  
Un array es una colección de items de datos, llamados elementos, asociados a un único nombre de variable.

Diseñados para:

Facilitar la programación y proveer buena performance

Almacenar y manipular grandes colecciones de datos

Simplificar la tarea de nombrar y referenciar items individuales en una colección de datos

Permitir la manipulación de una colección entera de datos con una simple sentencia

In [10]:
np.array([])

array([], dtype=float64)

In [11]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [38]:
arr3 = [[1,2,3,"hola"]]
arr3

[[1, 2, 3, 'hola']]

**¿Qué diferencia encuentran entre arr2 y arr3?**

In [25]:
arr1[0]

1

In [ ]:
arr1[len(arr1)] 

Los índices van desde el 0 a (cantidad de elementos - 1)

**Tipos de Indexación**  
Existen tres tipos de indexación:  
a) slicing: arr1[start:stop:step]. El step puede no estar, si no está es 1.  
b) Fancy slicing: Usar una máscara de índices arr1[[0,3,5]]  
c) Boolean indexing: Usar una máscara de elementos verdaderos y falsos.  


In [29]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr1[0:5:1]

array([1, 2, 3, 4, 5])

In [31]:
indices = [0,3,5]
arr1[indices] #indices 0, 3, 5

array([1, 4, 6])

In [32]:
arr1 > 4

array([False, False, False, False,  True,  True,  True,  True])

In [36]:
arr1%2==1

array([ True, False,  True, False,  True, False,  True, False])

In [35]:
arr1[arr1%2==1]

array([1, 3, 5, 7])

Crear un array usando arrange [documentación](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [39]:
print(np.arange(10))
print(np.arange(3,11))
print(np.arange(3,11, 3))

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10]
[3 6 9]


In [41]:
one_d_array = np.arange(10)
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
print(one_d_array[0::3])

[0 3 6 9]


In [46]:
aa = np.array([1,2,4,5,3,2,9])
aa[::-1]


array([9, 2, 3, 5, 4, 2, 1])

In [50]:
a = one_d_array[::-1]
a[a % 2 == 0]

array([8, 6, 4, 2, 0])

In [61]:
mask_pair_number = one_d_array % 2 == 0
mask_pair_number

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [62]:
one_d_array[mask_pair_number]

array([0, 2, 4, 6, 8])

In [63]:
a = np.array([0, 1, 2])
b = 5
a + b

array([5, 6, 7])

In [53]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# linea 2 de la imagen:
#np.ones crea un vector o matriz con todos los valores en 1
#np.zeros crea un vector o matriz con todos los valores en 0

a = np.ones((3, 3))
print("*"*4)
print(a)
print("*"*4)
b = np.array([0, 1, 2])
print(b)
print("*"*4)
print(a + b)
print("*"*4)

****
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
****
[0 1 2]
****
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
****


In [60]:
a[0][1]

1.0

In [62]:
a = np.array([[0], [1], [2]])
print('\na.shape:', a.shape)
print('a:')
print(a)

b = np.array([0, 1, 2])
print('\nb.shape:', b.shape)
print('b:')
print(b)

print('\na+b:')
print(a+b)
print((a+b).shape)



a.shape: (3, 1)
a:
[[0]
 [1]
 [2]]

b.shape: (3,)
b:
[0 1 2]

a+b:
[[0 1 2]
 [1 2 3]
 [2 3 4]]
(3, 3)


## Funciones de agregación

Suelen expresarse como métodos del objeto array. En general, tienen como consecuencia disminuir las dimensiones del arreglo y son muy utilizados en matemáticas y física. <br>
La siguiente tabla muestra los más utilizados, puede encontrar la documentación [aquí](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#calculation).

| Operación | Descripción |
|:----------|:------------|
| `a.sum()`    | Retorna la suma del arreglo en el eje dado |
| `a.min()`    | Retorna el valor mínimo de un eje |
| `a.mean()`   | Retorna la media aritmética en un eje dado |
| `a.var()`    | Retorna la varianza en un eje dado|
| `a.std()`    | Retorna la desviación estándar en un eje dado |
| `a.prod()`   | Retorna el producto en un eje dado |
| `a.argmin()` | Retorna el índice donde ocurren los valores mínimos de cada eje |
| `a.ptp()`    | Valor pico a pico en un eje |
| `a.conj()`   | Retorna el conjugado complejo de todos los elementos |
| `a.round()`  | Retorna el valor redondeado de cada elemento |
| `a.trace()`  | Retorna la suma de las diagonales del arreglo |
| `a.argmax()` | Retorna el índice donde ocurren los valores máximos de cada eje |
| `a.cumsum()` | Retorna la suma acumulativa en un eje dado |
| `a.cumprod()`| Retorna el producto acumulativo en un eje dado |

In [67]:
contentFolder = "./Data"
#Get Data 
urlOrdersTitanicTrain = "https://drive.google.com/uc?id=1hZAS7bZndWwIhpi7231sdQPfIfMhKyjb"
r = requests.get(urlOrdersTitanicTrain)
open("{}/titanic_train.txt".format(contentFolder), "wb").write(r.content)

61194

## Diccionario de los campos de la base
**Survived** -> Survival - target (0 = No, 1 = Si)\
**Pclass** -> Ticket Class (1 = 1st, 2 = 2nd, 3 = 3rd)\
**Sex** -> Sex (male, female)\
**Age** -> Age in years\
**SibSp** -> of siblings / spouses aboard the Titanic\
**Parch** -> of parents / children aboard the Titanic\
**Ticket** -> ticket number\
**Fare** -> Passenger Fare (Tarifa)\
**Cabin** -> cabin Number\
**Embarked** -> Port of Embarkation (C = Cherbourg, Q = Queenstown, S = Southampton)

Para Levantar una base usando Numpy puedo utilizar la función genfromtxt
[documentacion](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html)

In [96]:
#levantar Datos usando Numpy
data = np.genfromtxt("C:/Users/Diego/Documents/proyectos/sales_data_sample_excercise.csv", skip_header=1, delimiter='\t', dtype=str)


array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [90]:
data[:,0].astype(int)

891

Los campos de la base pueden sufrir cambios en sus tipos de datos, para realizar esto, necesito usar la función astype()

A diferencia de un array, un numpy array todos sus elementos poseen el mismo tipo de datos

In [25]:
for x in np.array([1,2,3,4, "Hhola"]):
    print(type(x))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [26]:
for x in [1,2,3,4,"hola"]:
    print(type(x))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>


In [29]:
#selecciono todos las filas y la columna 0 y cambio el tipo de datos
data[:,0].astype(int)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18